### ISSUE TITLE
Could not setup the database

### ISSUE THREAD

**Issue by bvn13** [mintster/nixmash-blog#1]
```
$ mysql -h localhost -u root -p blog < mysqlsetup.sql
Enter password:
ERROR 1146 (42S02) at line 117: Table 'blog.UserConnection' doesn't exist
```

**Comment by bvn13** [comment]
fixed by changing line
```
CREATE UNIQUE INDEX UserConnectionProviderUser ON UserConnection(providerId, providerUserId);
```
into the folowing:
```
CREATE UNIQUE INDEX UserConnectionProviderUser ON userconnection(providerId, providerUserId);
```

**Comment by mintster** [comment]
Thanks for the info. I suggest rather than update the script that you change the MySQL database to Case Insensitive. Essentially you add the following to your mysql.cnf.

```sql
[mysqld]
lower_case_table_names=1
```
I blogged on the topic here:

http://nixmash.com/post/the-saga-of-the-case-insensitive-mysql-table-name
